import numpy as np
from numpy.typing import NDArray

class Dataset:
    def __init__(self, records: NDArray[np.float64], targets: NDArray[np.float64]) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def records(self) -> NDArray[np.float64]: ...
    @property
    def targets(self) -> NDArray[np.float64]: ...

class LinearRegression:
    def __init__(self, fit_intercept: bool = True) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def coefficients(self) -> NDArray[np.float64]: ...
    @property
    def intercept(self) -> float: ...

class LogisticRegression:
    def __init__(self, fit_intercept: bool = True) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> tuple[int, int]: ...
    @property
    def coefficients(self) -> NDArray[np.float64]: ...
    @property
    def intercept(self) -> float: ...

class KMeans:
    def __init__(self, n_clusters: int) -> None: ...
    def fit(self, records: NDArray[np.float64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...

class DBSCAN:
    def __init__(self, eps: float, min_samples: int) -> None: ...
    def fit(self, records: NDArray[np.float64]) -> None: ...
    def labels(self) -> NDArray[np.int64]: ...
    def n_clusters(self) -> int: ...

class GaussianMixture:
    def __init__(self, n_components: int) -> None: ...
    def fit(self, records: NDArray[np.float64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...

class PCA:
    def __init__(self, n_components: int | None = None) -> None: ...
    def fit(self, records: NDArray[np.float64]) -> None: ...
    def transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def explained_variance_ratio(self) -> NDArray[np.float64]: ...

class StandardScaler:
    def __init__(self, with_mean: bool = True, with_std: bool = True) -> None: ...
    def fit(self, records: NDArray[np.float64]) -> None: ...
    def transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...

class DecisionTreeRegressor:
    def __init__(self, max_depth: int | None = None) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...

class DecisionTreeClassifier:
    def __init__(self, max_depth: int | None = None) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...

class RandomForestRegressor:
    def __init__(self, n_estimators: int = 100, max_depth: int | None = None) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...

class RandomForestClassifier:
    def __init__(self, n_estimators: int = 100, max_depth: int | None = None) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...

class GradientBoostingRegressor:
    def __init__(
        self,
        n_estimators: int = 100,
        learning_rate: float = 0.1,
        max_depth: int | None = 3,
    ) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...

class GradientBoostingClassifier:
    def __init__(
        self,
        n_estimators: int = 100,
        learning_rate: float = 0.1,
        max_depth: int | None = 3,
    ) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> tuple[int, int]: ...

class AdaBoostClassifier:
    def __init__(self, n_estimators: int = 50, learning_rate: float = 1.0) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> tuple[int, int]: ...

class KNeighborsRegressor:
    def __init__(self, n_neighbors: int) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...

class KNeighborsClassifier:
    def __init__(self, n_neighbors: int) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...

class RidgeRegression:
    def __init__(self, alpha: float, fit_intercept: bool = True) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def coefficients(self) -> NDArray[np.float64]: ...
    @property
    def intercept(self) -> float: ...

class LassoRegression:
    def __init__(self, alpha: float, fit_intercept: bool = True) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def coefficients(self) -> NDArray[np.float64]: ...
    @property
    def intercept(self) -> float: ...

class ElasticNetRegression:
    def __init__(self, alpha: float, l1_ratio: float, fit_intercept: bool = True) -> None: ...
    def fit(self, dataset: Dataset) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def coefficients(self) -> NDArray[np.float64]: ...
    @property
    def intercept(self) -> float: ...

class LinearDiscriminantAnalysis:
    def __init__(self) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> NDArray[np.int64]: ...

class GaussianNaiveBayes:
    def __init__(self) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> NDArray[np.int64]: ...

class MultinomialNaiveBayes:
    def __init__(self, alpha: float = 1.0, fit_prior: bool = True) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> NDArray[np.int64]: ...

class BernoulliNaiveBayes:
    def __init__(
        self,
        alpha: float = 1.0,
        fit_prior: bool = True,
        binarize: float | None = 0.0,
    ) -> None: ...
    def fit(self, records: NDArray[np.float64], targets: NDArray[np.int64]) -> None: ...
    def predict(self, records: NDArray[np.float64]) -> NDArray[np.int64]: ...
    def predict_proba(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> NDArray[np.int64]: ...

class SimpleImputer:
    @staticmethod
    def mean() -> SimpleImputer: ...
    @staticmethod
    def median() -> SimpleImputer: ...
    @staticmethod
    def constant(value: float) -> SimpleImputer: ...
    def fit(self, records: NDArray[np.float64]) -> None: ...
    def transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    @property
    def fill_values(self) -> NDArray[np.float64]: ...

class PolynomialFeatures:
    def __init__(
        self,
        degree: int,
        include_bias: bool = True,
        interaction_only: bool = False,
    ) -> None: ...
    def fit(self, records: NDArray[np.float64]) -> None: ...
    def transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def fit_transform(self, records: NDArray[np.float64]) -> NDArray[np.float64]: ...

class LabelEncoder:
    def __init__(self) -> None: ...
    def fit(self, labels: list[str]) -> None: ...
    def transform(self, labels: list[str]) -> NDArray[np.int64]: ...
    def inverse_transform(self, codes: list[int]) -> list[str]: ...
    @property
    def classes(self) -> list[str]: ...

class OneHotEncoder:
    def __init__(self, drop_first: bool = False) -> None: ...
    def fit(self, labels: list[str]) -> None: ...
    def transform(self, labels: list[str]) -> NDArray[np.float64]: ...
    @property
    def classes(self) -> list[str]: ...

def train_test_split(
    dataset: Dataset,
    test_fraction: float,
    seed: int = 42,
    shuffle: bool = True,
) -> tuple[Dataset, Dataset]: ...

class KFold:
    def __init__(self, n_splits: int, shuffle: bool = False, seed: int = 42) -> None: ...
    def split(
        self, n_samples: int
    ) -> list[tuple[NDArray[np.int64], NDArray[np.int64]]]: ...

class StratifiedKFold:
    def __init__(self, n_splits: int, shuffle: bool = False, seed: int = 42) -> None: ...
    def split(
        self, targets: list[int]
    ) -> list[tuple[NDArray[np.int64], NDArray[np.int64]]]: ...

def accuracy_score(actual: NDArray[np.int64], predicted: NDArray[np.int64]) -> float: ...
def mean_squared_error(actual: NDArray[np.float64], predicted: NDArray[np.float64]) -> float: ...
def r2_score(actual: NDArray[np.float64], predicted: NDArray[np.float64]) -> float: ...
def precision_score(actual: NDArray[np.int64], predicted: NDArray[np.int64]) -> float: ...
def recall_score(actual: NDArray[np.int64], predicted: NDArray[np.int64]) -> float: ...
def f1_score(actual: NDArray[np.int64], predicted: NDArray[np.int64]) -> float: ...
def roc_auc_score(
    actual: NDArray[np.int64],
    positive_probabilities: NDArray[np.float64],
    positive_label: int,
) -> float: ...
def confusion_matrix(
    actual: NDArray[np.int64], predicted: NDArray[np.int64]
) -> tuple[NDArray[np.int64], NDArray[np.int64]]: ...
